StartupEvents.registry('fluid', event => {event.create('molten_iron')
.displayName('Molten Iron')
.stillTexture('kubejs:block/fluid_pyrotheum_still')
.flowingTexture('kubejs:block/fluid_pyrotheum_flow')
.thickTexture(0xb6420e)
.luminosity(15)
.noBucket()
.noBlock()
})
