StartupEvents.registry('fluid', event => {event.create('pyrotheum')
.displayName('Pyrotheum')
.stillTexture('kubejs:block/fluid_pyrotheum_still')
.flowingTexture('kubejs:block/fluid_pyrotheum_flow')
.bucketColor(0xffdc25)
.luminosity(15)
.temperature(3000)
.viscosity(3000)
})