ServerEvents.recipes(event => {
    event.remove({ output: 
        [
            "exdeorum:warped_crucible",
            "exdeorum:crimson_crucible",
            "exdeorum:oak_crucible",
            "exdeorum:spruce_crucible",
            "exdeorum:birch_crucible",
            "exdeorum:jungle_crucible",
            "exdeorum:acacia_crucible",
            "exdeorum:dark_oak_crucible",
            "exdeorum:bamboo_crucible",
            "torchmaster:megatorch",
            "mekanismgenerators:heat_generator",
            "tconstruct:grout",
            "tconstruct:nether_grout",
            "minecraft:composter",
            "minecraft:diamond_helmet",
            "minecraft:diamond_chestplate",
            "minecraft:diamond_leggings",
            "minecraft:diamond_boots",
            "minecraft:netherite_helmet",
            "minecraft:netherite_chestplate",
            "minecraft:netherite_leggings",
            "create:netherite_diving_boots",
            "exdeorum:porcelain_bucket"
        ]
     });    
});
